### ISSUE TITLE
Runtime Error: dictionary changed size during iteration [Bug] 

### ISSUE THREAD

**Issue by SakuraJensen** [canisminor1990/sd-webui-lobe-theme#262]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Runtime Error after intializing lobe.  Results in the extra network bar breaking.

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/33555092/ddefba86-5b56-4d57-bf61-49379456f2ad)

The only way I have been able to fix the issue is to delete all of the .info and .preview files from civitai helper.  The error will go away until the next launch.

After initializing lobe I get the following error in my console: 

```
[Lobe]: Initializing Lobe
Startup time: 41.0s (import torch: 4.3s, import gradio: 1.7s, import ldm: 0.9s, other imports: 3.3s, opts onchange: 0.3s, setup codeformer: 0.2s, list SD models: 0.4s, load scripts: 24.1s, create ui: 1.1s, gradio launch: 4.5s).
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\modules\ui_extra_networks.py", line 348, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\stable-diffusion-webui\modules\ui_extra_networks.py", line 348, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\stable-diffusion-webui\modules\ui_extra_networks.py", line 122, in create_html
    for item in self.list_items():
  File "D:\stable-diffusion-webui\modules\ui_extra_networks_checkpoints.py", line 17, in list_items
    for index, (name, checkpoint) in enumerate(sd_models.checkpoints_list.items()):
RuntimeError: dictionary changed size during iteration.

```

My Current extensions:
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/33555092/a4c7b390-615d-41fb-9ae7-c72f2bdedec8)

### 🚦 期望结果 | Expected Behavior

The Extra Network bar to work as expected.

### 📷 复现步骤 | Recurrence Steps

Start webui-user with civitai helper and lobehub theme.

### 📝 补充信息 | Additional Information

Thank you for all your hard work :) I cannot imagine going without your theme again.

**Comment by SakuraJensen** [comment]
Issue seems to have been fixed in latest version.
