### ISSUE TITLE
[Bug] Setting options can't be loaded out

### ISSUE THREAD

**Issue by StormyOrange** [canisminor1990/sd-webui-lobe-theme#271]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

The theme extension settings page does not load after upgrading to the latest version of the extension

### 📷 复现步骤 | Recurrence Steps
*** Error loading script: settings.py
    Traceback (most recent call last):
      File "I:\Stable Diffusion\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "I:\Stable Diffusion\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "I:\Stable Diffusion\extensions\sd-webui-lobe-theme\scripts\settings.py", line 11, in <module>
        from scripts.lib.api import LobeApi
      File "I:\Stable Diffusion\extensions\sd-webui-lobe-theme\scripts\lib\api.py", line 8, in <module>
        from scripts.lib.locale import LobeLocale
    ModuleNotFoundError: No module named 'scripts.lib.locale'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

_No response_

**Comment by Array-Cats** [comment]
Same Bug

2023-07-16 20:05:30,374 - ControlNet - INFO - ControlNet v1.1.232
*** Error loading script: settings.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\stable-diffusion-webui\extensions\sd-webui-lobe-theme\scripts\settings.py", line 11, in <module>
        from scripts.lib.api import LobeApi
      File "W:\stable-diffusion-webui\extensions\sd-webui-lobe-theme\scripts\lib\api.py", line 8, in <module>
        from scripts.lib.locale import LobeLocale
    ModuleNotFoundError: No module named 'scripts.lib.locale'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
Loading weights [9e4f6f7a28] from W:\stable-diffusion-webui\models\Stable-diffusion\2D\sweetMix_v21.safetensors
