### ISSUE TITLE
setting选项卡无法打开

### ISSUE THREAD

**Issue by coderxzh** [canisminor1990/sd-webui-lobe-theme#275]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

设置按钮点击无法打开
Error loading script: settings.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.1\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4.1\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-lobe-theme\scripts\settings.py", line 10, in <module>
        from scripts.lib.lobe_log import LobeLog
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-lobe-theme\scripts\lib\lobe_log.py", line 19, in <module>
        LobeLog = LobeLogClass()
      File "D:\sd-webui-aki-v4.1\extensions\sd-webui-lobe-theme\scripts\lib\lobe_log.py", line 9, in __init__
        self.logging_enabled = shared.cmd_opts.lobe_debug
    AttributeError: 'Namespace' object has no attribute 'lobe_debug'

**Comment by canisminor1990** [comment]
更到最新了么？

**Comment by coderxzh** [comment]
已更新为最新版，打开设置后，设置选项卡不显示，浏览器界面黑屏了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月16日(星期天) 晚上11:50
收件人: "canisminor1990/sd-webui-lobe-theme";
抄送: "Author";
主题: Re: [canisminor1990/sd-webui-lobe-theme] setting选项卡无法打开 (Issue #275)





 
更到最新了么？
 
&mdash;

**Comment by xxyyboy** [comment]
同样的错误，
ModuleNotFoundError: No module named 'scripts.lib.lobe_log'

文件内的引用：
from scripts.lib.lobe_log import LobeLog

**Comment by CacaoRick** [comment]
不知道是不是同一個問題
```
*** Error loading script: settings.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/sd-webui-lobe-theme/scripts/settings.py", line 10, in <module>
        from scripts.lib.lobe_log import LobeLog
      File "/stable-diffusion-webui/extensions/sd-webui-lobe-theme/scripts/lib/lobe_log.py", line 19, in <module>
        LobeLog = LobeLogClass()
      File "/stable-diffusion-webui/extensions/sd-webui-lobe-theme/scripts/lib/lobe_log.py", line 9, in __init__
        self.logging_enabled = shared.cmd_opts.lobe_debug
    AttributeError: 'Namespace' object has no attribute 'lobe_debug'

```
